version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken
    HOST: prod/sonar:HOST
    Organization: prod/sonar:Organization
    Project: prod/sonar:Project
phases:
  #install:
   # runtime-versions:
    #  java: corretto8
  pre_build:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - mvn clean package  
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - mv target/*.war my-web-app.war

artifacts:
  files:
    - my-web-app.war  
    - target/*/*
  discard-paths: yes  

reports: 
  SurefireReports:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
    
  #JacocoReports:
   # files:
    #  - '**/*'
    #base-directory: 'target/site/jacoco-both/*'
